### ISSUE TITLE
Components with IEC style symbols

### ISSUE THREAD

**Issue by b-a-9-0** [gsuberland/altium_jlcpcb_libraries#1]
Thanks for this tremendous work! Would it be possible to also supply the libraries with IEC style symbols (e. g. for resistors)? These are mainly used in europe.

**Comment by gsuberland** [comment]
I'll consider it for whenever I update the library, but it's a low priority for me.

**Comment by gsuberland** [comment]
This has been done in the 2024-10-27 release. Altium now has a mode feature to select alternate symbols, and I have generated the resistor symbols to include an IEC mode symbol.
