### ISSUE TITLE
possible to get an updated version ?

### ISSUE THREAD

**Issue by manuprendlair** [gsuberland/altium_jlcpcb_libraries#2]
Hi, this is Manu from France.
Are you able to provide an up to date version ?

Regards

**Comment by gsuberland** [comment]
They are pretty outdated now. I am hoping to update them soon, since I am starting to run into problems while using them myself, but I really can't guarantee anything.

**Comment by manuprendlair** [comment]
I understand.
Thanks for your work.

Regards


Le jeu. 2 mai 2024, 07:23, Graham Sutherland ***@***.***> a
écrit :

**Comment by clemrdh** [comment]
Any updates ? 🙏

**Comment by clemrdh** [comment]
Maybe you can share the script so we can also update by ourselves ?

**Comment by gsuberland** [comment]
I have updated the library.
